import type { GeoPointFeature } from '@zlayer/contracts';

/** FAA VOR Candidate Retention List, 2026-02-24 (594 stations).
 * Source: https://www.faa.gov/sites/faa.gov/files/VOR%20Candidate%20Retention%20List%202026-02-24.xlsx
 * Workbook SHA-256: fb283123fb1adc54fcf0811f19887939988d9bee2927724ed4e89e2e8e5aeaf7
 * Extracted columns A (ID) and D (ST); candidate retention is not reception status.
 * Keep the state in the identity so foreign stations with reused IDs cannot match.
 */
export const MON_VOR_REFERENCE_DATE = '2026-02-24';
const retained = new Set(`
ABI:TX ABQ:NM ABR:SD ACH:NM ACK:MA ACO:OH ACT:TX ACV:CA ACY:NJ ADM:OK AEX:LA AGJ:TX AHN:GA AIA:NE AIR:OH
AKO:CO ALB:NY ALD:SC ALI:TX ALO:IA ALS:CO ALW:WA ANW:NE ANX:MO APE:OH APN:MI ARD:PA ARG:AR ART:NY AST:OR
ATR:DE AUG:ME AVE:CA AXC:IL AXN:MN AYS:GA BAE:WI BAF:MA BAL:MD BAM:NV BCE:UT BFF:NE BFM:AL BFV:OK BGR:ME
BGS:TX BIB:IL BIH:CA BIL:MT BIS:ND BJB:WI BJC:CO BKE:OR BLD:NV BLF:WV BLH:CA BNA:TN BOI:ID BOS:MA BOY:WY
BPI:WY BQS:MO BQU:NV BQZ:CO BRK:CO BRL:IL BRV:VA BSV:OH BTG:WA BTV:VT BTY:NV BUM:MO BVL:UT BVO:OK BWD:TX
BXK:AZ BYI:ID BYP:TX BZA:CA BZM:NC BZN:MT CAE:SC CAM:NY CCC:NY CDS:TX CEC:CA CEW:FL CEZ:CO CFB:NY CGT:IL
CHE:CO CHS:SC CID:IA CIM:NM CKB:WV CKV:TN CKW:WY CLL:TX CMA:CA CME:NM CMI:IL CMX:MI CNG:KY CNM:NM CNX:NM
COD:WY CON:NH COT:TX COU:MO CPN:MT CRE:SC CRG:FL CRL:MI CRP:TX CSI:TX CTB:MT CTF:SC CTR:MA CUS:NM CVA:IA
CVE:TX CVO:OR CVV:WA CWK:TX CYN:NJ CYS:WY CZI:WY DAG:CA DBL:CO DBN:GA DBQ:IA DBS:ID DCA:DC DDC:KS DDY:WY
DGD:MO DHP:FL DHT:TX DIK:ND DJB:OH DLH:MN DLL:WI DLN:MT DMN:NM DNJ:ID DNW:WY DPA:IL DPK:NY DPR:SD DQN:OH
DQO:DE DRK:AZ DRO:CO DSD:OR DSM:IA DTA:UT DUG:AZ DVC:CO DVV:CO EAT:WA EAU:WI ECG:NC ECS:WY EED:CA EHF:CA
EHK:UT EKN:WV EKR:CO ELB:CA ELD:AR ELN:WA ELP:TX ELW:SC ELY:NV EMG:LA EMI:MD EMP:KS ENE:ME ENI:CA ENL:IL
ENO:DE EPH:WA ESC:MI ETL:CO ETX:PA EUF:AL EUG:OR EVW:WY EWC:PA EWM:TX EWN:NC EWO:KY EYW:FL FAK:VA FAM:MO
FAR:ND FAY:NC FBR:WY FCA:MT FDK:MD FFT:KY FFU:UT FGT:MN FIM:CA FJS:CA FKL:PA FLG:AZ FLL:FL FLW:CA FMG:NV
FNT:MI FOT:CA FQF:CO FRA:CA FSD:SD FSM:AR FST:TX FTI:NM FTZ:MO FUZ:TX FWA:IN FZT:TX GAD:AL GBN:AZ GCC:WY
GCK:KS GCN:AZ GDM:MA GEE:NY GEF:FL GEG:WA GEP:MN GFK:ND GFS:CA GGG:TX GGW:MT GLH:MS GLJ:CA GLL:CO GMN:CA
GNV:FL GON:CT GPT:MS GPZ:MN GRB:WI GRI:NE GSO:NC GTF:MT GUP:NM GVE:VA GVO:CA GZG:VA HAR:PA HBR:OK HBU:CO
HCH:TN HCM:VA HCT:NE HDF:CA HEC:CA HFD:CT HGO:CO HGR:MD HIA:MT HIB:MN HLC:KS HLG:WV HLN:MT HLV:MO HNW:CA
HOB:NM HOT:AR HPW:VA HQM:WA HRL:TX HRO:AR HRV:LA HUP:TX HUT:KS HVE:UT HVQ:WV HVR:MT HYK:KY HYP:CA HZN:NV
IAH:TX IDA:ID IGB:MS IGM:AZ IGN:NY IIP:WY IIU:KY ILA:CA ILC:NV ILM:NC ILR:OR IMB:OR INK:TX INL:MN INW:AZ
IOW:IA IPL:CA IRQ:SC IRW:OK ISN:ND ISO:NC IWA:AZ IWD:MI JAC:WY JBR:AR JCT:TX JFK:NY JHW:NY JLI:CA JMS:ND
JNC:CO JOT:IL JPU:WV JST:PA LAA:CO LAL:FL LAR:WY LAS:NV LAW:OK LAX:CA LBB:TX LBF:NE LBY:MS LCH:LA LCU:UT
LEV:LA LFK:TX LFV:MA LGC:GA LHO:UT LHS:CA LIB:NC LIN:CA LIT:AR LKT:ID LKV:OR LLA:LA LLC:NV LMN:IA LMT:OR
LNK:NE LOZ:KY LRD:TX LRP:PA LSU:LA LTJ:WA LVM:MT LVT:TN LWL:NV LWT:MT MAD:CT MAF:TX MAI:FL MBS:MI MBW:WY
MCB:MS MCI:MO MCK:NE MCW:IA MEI:MS MFE:TX MGM:AL MGW:WV MHE:SD MHF:TX MHK:KS MHZ:MS MKL:TN MLB:FL MLD:ID
MLF:UT MLP:ID MLS:MT MLT:ME MLU:LA MMB:OK MMM:NV MOD:CA MOL:VA MOT:ND MPV:VT MQG:ID MQO:CA MQP:TX MRB:WV
MRF:TX MSN:WI MSO:MT MTJ:CO MTU:UT MVA:NV MVC:AL MVY:MA MWH:WA MYV:CA MZB:CA NUN:FL OAK:CA OAL:NV OBK:IL
OCF:FL OCN:CA OCS:WY ODG:OK ODI:MN OED:OR OFK:NE OGD:UT OKM:OK OKW:AL OLM:WA OLS:AZ OLU:NE OMN:FL ONM:NM
ONP:OR ORF:VA ORL:FL OSH:WI OSI:CA OTB:MS OTH:OR OTK:GA OTO:NM OVR:IA OWB:KY PBF:AR PBI:FL PCU:MS PDT:OR
PDZ:CA PEQ:TX PER:OK PGA:AZ PGO:OK PGS:AZ PGY:CA PHP:SD PIA:IL PIE:FL PIH:ID PIO:NM PIR:SD PKE:CA PMD:CA
PNH:TX POM:CA PQI:ME PRB:CA PSB:PA PSC:WA PSP:CA PSX:TX PUB:CO PUC:UT PUW:WA PVD:RI PVW:TX PWA:OK PXN:CA
PXR:AZ PXV:IN PYE:CA PZD:GA RAL:CA RAP:SD RAV:PA RBG:OR RBL:CA RBV:NJ RDD:CA RDU:NC REO:OR RHI:WI RIC:VA
RIL:CO RIW:WY RLG:CO RLY:WY RMG:GA ROC:NY RQZ:AL RRS:AL RSG:TX RSK:NM RSW:FL RWF:MN RZC:AR RZS:CA SAC:CA
SAF:NM SAT:TX SAU:CA SAV:GA SAW:MI SAX:NJ SBI:TX SBJ:NJ SBV:VA SDO:NV SDZ:NC SEA:WA SEG:PA SEY:RI SFL:TX
SFO:CA SGD:CA SGF:MO SHB:IN SHR:WY SHY:MO SIE:NJ SJC:CA SJI:AL SJN:AZ SJT:TX SLI:CA SLN:KS SMO:CA SNS:CA
SNY:NE SOT:TN SPA:SC SPI:IL SPS:TX SPW:IA SQS:MS SRQ:FL SSF:TX SSI:GA SSM:MI SSO:AZ STJ:MO STL:MO STV:TX
SVC:NM SWO:OK SWR:CA SXC:CA SYI:TN SYR:NY SZW:FL TAS:NM TBC:AZ TBD:LA TBE:CO TCC:NM TCH:UT TCS:NM TFD:AZ
TNP:CA TNU:IA TNV:TX TOP:KS TOU:WA TPH:NV TQA:TX TRM:CA TST:NE TTE:CA TTT:TX TUL:OK TUS:AZ TVC:MI TVF:MN
TWF:ID TXC:CO TXK:TX TXO:TX TYI:NC TYR:TX UBG:OR UJM:AR VCN:NJ VCT:TX VEL:UT VHP:IN VIH:MO VIO:MI VKZ:FL
VNA:GA VNY:CA VTU:CA VUH:TX VUZ:AL VXV:TN XUB:OH YKM:WA ZUN:NM
`.trim().split(/\s+/));

export function isMonVor(feature: GeoPointFeature): boolean {
  const { ident, state, country } = feature.properties;
  if (country && !['US', 'USA', 'UNITED STATES'].includes(String(country).trim().toUpperCase())) return false;
  return retained.has(`${String(ident ?? '').trim().toUpperCase()}:${String(state ?? '').trim().toUpperCase()}`);
}
