import { readFile, writeFile } from 'node:fs/promises';
import { palettes, themeCss } from './theme/palette';

const logo = await readFile(new URL('../public/logo.svg', import.meta.url), 'utf8');
const outputs = [
  ['../src/core/theme/tokens.css', themeCss()],
  ['../public/logo-light.svg', '<!-- Generated by tools/generate-theme.ts from logo.svg. -->\n'
    + logo.replaceAll('#ECF7FD', palettes.light['text-primary']!)
      .replace('designed for #07111f', 'with theme-derived ink for light surfaces')],
] as const;
for (const [path, content] of outputs) {
  const target = new URL(path, import.meta.url);
  if (process.argv.includes('--check')) {
    if (await readFile(target, 'utf8').catch(() => '') !== content) {
      console.error(`${path} is stale. Run npm run theme:generate.`);
      process.exitCode = 1;
    }
  } else await writeFile(target, content);
}
